# Generated by Django 3.1.1 on 2023-08-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('language', models.CharField(choices=[('python', 'Python'), ('js', 'JavaScript'), ('java', 'Java')], default='python', max_length=100)),
                ('style', models.CharField(choices=[('bild', 'Bold'), ('underline', 'Underline'), ('friendly', 'Friendly')], default='friendly', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
